# Generated by Django 3.0.1 on 2020-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='files')),
            ],
            options={
                'verbose_name_plural': 'Resume',
                'db_table': 'tbl_resume',
            },
        ),
    ]
